/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTrackingRouteImport } from './routes/app.tracking'
import { Route as AppRemindersRouteImport } from './routes/app.reminders'
import { Route as AppProductionRouteImport } from './routes/app.production'
import { Route as AppPlanningRouteImport } from './routes/app.planning'
import { Route as AppOnePagerRouteImport } from './routes/app.one-pager'
import { Route as AppDeliveryRouteImport } from './routes/app.delivery'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCostingRouteImport } from './routes/app.costing'
import { Route as AppAdminRouteImport } from './routes/app.admin'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTrackingRoute = AppTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => AppRoute,
} as any)
const AppRemindersRoute = AppRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AppRoute,
} as any)
const AppProductionRoute = AppProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanningRoute = AppPlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => AppRoute,
} as any)
const AppOnePagerRoute = AppOnePagerRouteImport.update({
  id: '/one-pager',
  path: '/one-pager',
  getParentRoute: () => AppRoute,
} as any)
const AppDeliveryRoute = AppDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCostingRoute = AppCostingRouteImport.update({
  id: '/costing',
  path: '/costing',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AppAdminRoute
  '/app/costing': typeof AppCostingRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/delivery': typeof AppDeliveryRoute
  '/app/one-pager': typeof AppOnePagerRoute
  '/app/planning': typeof AppPlanningRoute
  '/app/production': typeof AppProductionRoute
  '/app/reminders': typeof AppRemindersRoute
  '/app/tracking': typeof AppTrackingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AppAdminRoute
  '/app/costing': typeof AppCostingRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/delivery': typeof AppDeliveryRoute
  '/app/one-pager': typeof AppOnePagerRoute
  '/app/planning': typeof AppPlanningRoute
  '/app/production': typeof AppProductionRoute
  '/app/reminders': typeof AppRemindersRoute
  '/app/tracking': typeof AppTrackingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AppAdminRoute
  '/app/costing': typeof AppCostingRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/delivery': typeof AppDeliveryRoute
  '/app/one-pager': typeof AppOnePagerRoute
  '/app/planning': typeof AppPlanningRoute
  '/app/production': typeof AppProductionRoute
  '/app/reminders': typeof AppRemindersRoute
  '/app/tracking': typeof AppTrackingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/admin'
    | '/app/costing'
    | '/app/dashboard'
    | '/app/delivery'
    | '/app/one-pager'
    | '/app/planning'
    | '/app/production'
    | '/app/reminders'
    | '/app/tracking'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/admin'
    | '/app/costing'
    | '/app/dashboard'
    | '/app/delivery'
    | '/app/one-pager'
    | '/app/planning'
    | '/app/production'
    | '/app/reminders'
    | '/app/tracking'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/admin'
    | '/app/costing'
    | '/app/dashboard'
    | '/app/delivery'
    | '/app/one-pager'
    | '/app/planning'
    | '/app/production'
    | '/app/reminders'
    | '/app/tracking'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/tracking': {
      id: '/app/tracking'
      path: '/tracking'
      fullPath: '/app/tracking'
      preLoaderRoute: typeof AppTrackingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reminders': {
      id: '/app/reminders'
      path: '/reminders'
      fullPath: '/app/reminders'
      preLoaderRoute: typeof AppRemindersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/production': {
      id: '/app/production'
      path: '/production'
      fullPath: '/app/production'
      preLoaderRoute: typeof AppProductionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/planning': {
      id: '/app/planning'
      path: '/planning'
      fullPath: '/app/planning'
      preLoaderRoute: typeof AppPlanningRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/one-pager': {
      id: '/app/one-pager'
      path: '/one-pager'
      fullPath: '/app/one-pager'
      preLoaderRoute: typeof AppOnePagerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/delivery': {
      id: '/app/delivery'
      path: '/delivery'
      fullPath: '/app/delivery'
      preLoaderRoute: typeof AppDeliveryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/costing': {
      id: '/app/costing'
      path: '/costing'
      fullPath: '/app/costing'
      preLoaderRoute: typeof AppCostingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppCostingRoute: typeof AppCostingRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDeliveryRoute: typeof AppDeliveryRoute
  AppOnePagerRoute: typeof AppOnePagerRoute
  AppPlanningRoute: typeof AppPlanningRoute
  AppProductionRoute: typeof AppProductionRoute
  AppRemindersRoute: typeof AppRemindersRoute
  AppTrackingRoute: typeof AppTrackingRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppCostingRoute: AppCostingRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDeliveryRoute: AppDeliveryRoute,
  AppOnePagerRoute: AppOnePagerRoute,
  AppPlanningRoute: AppPlanningRoute,
  AppProductionRoute: AppProductionRoute,
  AppRemindersRoute: AppRemindersRoute,
  AppTrackingRoute: AppTrackingRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
